version: '3'
services:
    app:
        stdin_open: true
        build: 
            dockerfile: Dockerfile
            context: .
        environment: 
            - OPENAI_API_KEY=$OPENAI_API_KEY
            - PORT=2000
        ports: 
            - '8000:2000'
